### ISSUE TITLE
Image styles are not generated unless field ui is enabled

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa_profile#38]
## To replicate

1. Run `drush si uiowa`.
2. Create a basic page.
3. In the WYSIWYG embed a new image.
4. Select one of the following image styles: thumbnail, medium, large.
5. Embed the image and save the node.

Upon saving you should see a broken image, however if you enable the field_ui the images will appear.

This issue is related to PR #37

**Comment by adamdelaney** [comment]
Once field_ui is enabled image styles can be derived even when field_ui is uninstalled again.

**Comment by adamdelaney** [comment]
The display plugin for thumbnail does not seem to work at all if implemented via media reference field even when the field_ui is turned on.

**Comment by adamdelaney** [comment]
This was an issue with DevDesktop and it's symlink usage to bypass sites.php. To resolve the issue you may either remove the symlink and add a sites.php entry or add the $setting['file_public_path'] to your site directory is.
