### ISSUE TITLE
Anchors in WYSIWYG

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa_profile#42]
There is a contrib module for this (https://www.drupal.org/project/anchor_link) but unfortunately it violates D.O guidelines (https://www.drupal.org/project/anchor_link/issues/2888087). It looks like there is a plan to extract this functionality from Panopoly and create a new Drupal 8 module for this that is implemented the Drupal 8 way https://www.drupal.org/project/panopoly/issues/2954904.

**Comment by adamdelaney** [comment]
My vote is that we allow the ID attribute for certain elements and then provide documentation on how people can link to those IDs by modifying the source.

**Comment by adamdelaney** [comment]
Looks like id's are available attributes on headings, so I'm closing this issue for now.
