### ISSUE TITLE
Change name of install profile

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa_profile#48]
## Issue ##
The name of the directory for the profile and the machine name of the profile do not match, which can be problematic as other projects assume the machine name of the profile is the same as profile directory when searching for dependencies (e.g., Superfish).

## Proposed solutions ##
1. **Change the Composer package name** from `uiowa/uiowa_profile` to `uiowa/uiowa` since the name of the directory a Composer package is downloaded into is the name of the package. This will also require updating composer.json in the [uiowa801 application repo](https://github.com/uiowa/uiowa801) to use the new package name.

2. **Change the machine name of the profile** to `uiowa_profile`.

3. **Change both the machine name of the profile and the Composer package name** to something else. Please post new name ideas in the comments.

## Todo ##
The selected solution is to change the name of the profile and Composer package to `Rusty`, which includes:

- Change the machine name of the profile to `rusty`
- Change the human-readable name of the profile to `Rusty`
- Update the profile's README
- Change the Composer package name to `rusty`
- Change the profile's GitHub repository name to `rusty`

**Comment by briand44** [comment]
kinnick

**Comment by genjohnson** [comment]
Burch: https://www.press-citizen.com/story/sports/college/iowa/hawkcentral/2018/04/18/university-football-iowa-live-mascot-burch-bear/499146002/

**Comment by genjohnson** [comment]
@richardbporter can the composer package name be different than the Git repo name? Since the name of the application repo was changed to `uiowa`, I'm wondering if there would be technical issues with using the package name `uiowa/uiowa` if we kept the Git repo name as `uiowa_profile`.

**Comment by markahrens** [comment]
If we want to be prepared for the possibility of multiple profile names, I would suggest Macbride, MacLean, Schaeffer and Jessup

**Comment by richardbporter** [comment]
amos, silas

https://uiowa.edu/homepage/university-iowa-presidents

**Comment by richardbporter** [comment]
@genjohnson Yea it probably should not be uiowa/uiowa at this point.

**Comment by markahrens** [comment]
rusty, after the sloth

**Comment by joewhitsitt** [comment]
skortdog (Frm Pres David Skorton's spray tag)

**Comment by joewhitsitt** [comment]
Burch (the bear)

https://www.press-citizen.com/story/sports/college/iowa/hawkcentral/2018/04/18/university-football-iowa-live-mascot-burch-bear/499146002/

**Comment by genjohnson** [comment]
Voltron

**Comment by genjohnson** [comment]
Rusty is the winner.
