### ISSUE TITLE
Update media entity embed button icon.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa_profile#54]
We are currently using the same button as core is using for the core image handling. Could be confusing for developers.

**Comment by briand44** [comment]
@ashybaye I see you updated the icon to use the one Dawn had uploaded to slack. I spoke with her this morning and it sounds like that icon is not labeled for reuse. We may need to come up with a different one. Sorry.

**Comment by adamdelaney** [comment]
I've re-created this icon so there are no usage issues.
