### ISSUE TITLE
We should use focal point for our custom image styles used in our media entity embed button.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa_profile#55]
Currently we have focal point enabled when embedding images but none of our image styles that are being rendered through our custom view modes use the focal point scale and crop.

**Comment by adamdelaney** [comment]
None of the image styles implemented via view_modes use a scale and crop so focal point does not make sense to use. If we decide to alter or create new view_modes that constrain the image aspect ratio, then I would suggest using a focal point scale and crop.

**Comment by genjohnson** [comment]
Based on the response from @adamdelaney, it sounds like this issue can be closed.

**Comment by genjohnson** [comment]
We've decided to leave this how it is for now, so marking as "postponed".

Once more functionality is built out there may be additional view modes that will render image styles using focal point scale and crop.

Focal point only guarantees that the point selected is included in the rendered image (it doesn't make that point the center of the image), which it technically is for images which are only scaled. So it doesn't necessarily go against editor expectations to continue having Focal Point when uploading an image to embed and not using Focal Point Scale & Crop effect for the image styles in the WYSIWYG.
