### ISSUE TITLE
Should we disable path form field for user creation

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa_profile#65]
Should we hide the path setting field on user creation? If we allow user creation to webmasters I'm not sure they should have the ability to alter the default user path.
<img width="814" alt="screen shot 2018-04-12 at 12 28 11 pm" src="https://user-images.githubusercontent.com/1016880/38693613-14e5a202-3e4d-11e8-9406-604514d64b44.png">
**uiowa.profile**
```
function uiowa_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['path']['#access'] = FALSE;
}
```

**Comment by genjohnson** [comment]
Restricting access to the URL alias field on the user form makes sense to me.

**Comment by richardbporter** [comment]
I'm not seeing this as a webmaster locally.

**Comment by adamdelaney** [comment]
This is for the user creation process not when editing a user. I can see the URL field during the user creation process as a webmster.

<img width="839" alt="screen shot 2018-04-16 at 10 59 49 am" src="https://user-images.githubusercontent.com/1016880/38821157-5fbc2538-4165-11e8-811a-c140dd8f298f.png">

**Comment by richardbporter** [comment]
We were missing the permission for webmasters to create URL aliases. I added it in that PR.
