### ISSUE TITLE
Choose sitemap generator

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/uiowa_profile#70]
There appears to be to competing modules for sitemap generation.
- [Simple Sitemap](https://www.drupal.org/project/simple_sitemap)
- [XML Sitemap](https://www.drupal.org/project/xmlsitemap)

Here is an article explaining some of the differences: http://gbyte.co/blog/drupal8-seo-simple_sitemap-vs-xmlsitemap-differences. Additionally, simple_sitemap has a stable release and xml_sitemap is currently in alpha.

**Comment by adamdelaney** [comment]
For now I've implemented simple_sitemap for the `seo` PR #72

**Comment by briand44** [comment]
I second the vote for simple_sitemap. It would be nice to get feedback from @dhannad.

**Comment by markahrens** [comment]
simple_sitemap looks like a good direction to go, it is more stable and has a good community around it. This is also something where if in a year, there is a better option, we should be able to switch out without too much pain.

**Comment by bspeare** [comment]
simple_sitemap looks good, I think that we can live without the automatic search engine submission feature.

**Comment by genjohnson** [comment]
It sounds like there's consensus on using simple_sitemap and it's been implemented, so I'm closing this issue.
