### ISSUE TITLE
Allow webmasters to submit sitemaps

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa_profile#75]
The simple sitemap module doesn't have built in functionality to submit sitemaps to search engines. We will need to figure out and document how webmasters should submit sitemaps to search engines.

**Comment by briand44** [comment]
I think it is probably fair to just document where the sitemap location is and point editors to Google's documentation on submitting sitemaps via Webmaster tools (Google Search Console). It would be a good practice for webmasters to be using this anyway.

**Comment by adamdelaney** [comment]
Google webmaster tools is a helpful resource. It can provide a lot of insight to crawl rates, errors and indexing. Additionally webmaster tools always site verification. This has traditionally been done by a developer for custom sites and documentation has been provided for standard sites. I think we should adopt 1 method for our d8 service offering. 

## Pros of client owned webmaster tools accounts.
- Removes the burden of managing this off a developer.
- Gives access to valuable data to the site owner/manager.

## Cons of client owned webmaster tools accounts.
- Several site owners may not create accounts to verify or submit sitemaps.
- Removes access to valuable data from developers.
- Site owners may not be technically inclined enough to manage any of these tasks.

**Comment by briand44** [comment]
The plan for now is to have webmasters submit sitemaps and verify their site themselves. We will provide documentation on how to handle this but that is a separate issue. https://github.com/uiowa/uiowa_profile/issues/90
