### ISSUE TITLE
Fix menu_block patches.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa_profile#82]
They do not apply at the application level.

**Comment by richardbporter** [comment]
I'm seeing: `Could not apply patch! Skipping. The error was: Cannot apply patch...` after running `composer install`.

**Comment by briand44** [comment]
Looks like this issue has a new patch https://www.drupal.org/node/2756675 https://www.drupal.org/files/issues/2018-05-01/menu_block-follow-2756675-43.patch
